apiVersion: v1
kind: ServiceAccount
metadata:
  name: lke-acl-operator
  namespace: lke-acl-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lke-acl-operator
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
      - update

  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lke-acl-operator
subjects:
  - kind: ServiceAccount
    name: lke-acl-operator
    namespace: lke-acl-operator
roleRef:
  kind: ClusterRole
  name: lke-acl-operator
  apiGroup: rbac.authorization.k8s.io
